# Generated by Django 3.2.9 on 2021-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_message', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=200)),
                ('course_term', models.CharField(max_length=20)),
                ('course_prize', models.CharField(max_length=200)),
            ],
        ),
    ]
