# Generated by Django 3.2.9 on 2021-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='technology',
            field=models.TextField(max_length=200),
        ),
    ]
