# Generated by Django 3.2.9 on 2021-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_center', '0002_alter_courses_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_mentor', models.ImageField(upload_to='mentors/')),
                ('name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=50)),
                ('technology', models.TextField(max_length=500)),
            ],
        ),
    ]
