# Generated by Django 3.2.9 on 2021-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_center', '0003_img_mentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='img_mentor',
            field=models.ImageField(blank=True, upload_to='mentors/'),
        ),
    ]
