# Generated by Django 3.2.9 on 2021-12-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_center', '0004_alter_mentors_img_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='mentors',
            options={'verbose_name': 'Mentor'},
        ),
    ]
